
name: AI Quality CI

on:
  pull_request:
    paths:
      - '**.py'
      - 'sonar_report.json'
      - 'run.sh'
  workflow_dispatch:

jobs:
  analyze-and-review:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: pip install openai requests

    - name: Run full analysis and review
      env:
        SMTP_PASSWORD: "${{ secrets.SMTP_PASSWORD }}"
        OPENAI_API_KEY: "${{ secrets.OPENAI_API_KEY }}"
        GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
        GITHUB_REPOSITORY: "${{ github.repository }}"
        PR_NUMBER: "${{ github.event.pull_request.number }}"
  
      run: |
        chmod +x run.sh
        ./run.sh
